

/* O ESCOPO EXTERNO FICA DISPONIVEL NO INTERNO, POREM O CONTRARIO NÃO É VERDADE, O ESCOPO INTERNO NÃO FICA DISPONIVEL NO EXTERNO */



/* AS FUNÇOES TEM ACESSO A VARIAVEIS GLOBAIS E AS VARIAVES INTERNAS (DELAS MESMAS) */


let pokemon = "Onix"; // CRIEI UMA VARIAVEL GLOBAL

function evoluir() {
    pokemon = "Steelix"; // REATRIBUI A VARIAVEL GLOBAL CRIADA DENTRO DESSA FUNÇÃO
}

console.log(pokemon); // ACESSO A VARIAVEL GLOBAL "Onix"
evoluir(); // CHAMO A FUNÇÃO
console.log(pokemon); // AQUI ACESSO A VARIAVEL REATRIBUIDA DENTRO DA FUNÇÃO "Steelix"

/* AO REATRIBUI-LA TENHO ACESSO */


/* EXEMPLO COM A VARIAVEL INTERNA */


function criarAnimal() {
    let animal = "Gato"; // CRIEI UMA VARIAVEL INTERNA, DENTRO DA FUNÇÃO
}

criarAnimal(); // CHAMO A FUNÇÃO
console.log(animal); // DA ERRO POIS animal NÃO ESTÁ DEFINIDO


/* OU SEJA, MESMO QUE EU CHAME A FUNÇÃO, NÃO TENHO ACESSO A VARIAVEL INTERNA DELA */


